services:
  - type: web
    name: ai-resume-assistant
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/main.py
    envVars:
      - key: TEXTGEARS_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    pythonVersion: 3.10.13
